services:
  # 1. Your NestJS Application
  api:
    build: .
    container_name: nest_api
    ports:
      - '3000:3000' # Exposes NestJS on port 3000 to the outside world
    env_file:
      - .env # Wskazuje plik źródłowy zmiennych
    environment:
      - DATABASE_URL # Docker automatycznie pobierze prawidłową wartość z pliku .env i wstrzyknie ją do kontenera
    depends_on:
      postgres:
        condition: service_healthy # NestJS container waits until PostgreSQL is 100% active and healthy

  # 2. Your PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: nest_postgres
    env_file:
      - .env # Dodane również tutaj, aby baza mogła odczytać DB_USER, DB_PASSWORD i DB_NAME
    environment:
      POSTGRES_USER: ${DB_USER} # Reads database admin user from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Reads database admin password from .env
      POSTGRES_DB: ${DB_NAME} # Reads database name from .env
    ports:
      - '5432:5432' # Exposes PostgreSQL on the standard port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Permanently stores database records so they don't vanish on container restarts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"] # Poprawione na $$, aby Docker poprawnie zinterpretował zmienną wewnątrz CMD-SHELL
      interval: 5s
      timeout: 5s
      retries: 5

  # 3. Prisma Studio as container
  studio:
    image: node:22-alpine
    container_name: prisma_studio
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '5555:5555' # Wystawia Prisma Studio na porcie 5555
    env_file:
      - .env
    environment:
      - DATABASE_URL # Bezpieczne pobranie zmiennej tak samo jak w usłudze api
    command: npx prisma studio --port 5555 --browser none
    depends_on:
      postgres:
        condition: service_healthy
  # 4. Custom MCP Server for AI Agents
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: nest_mcp_server
    command: tail -f /dev/null # <--- Zmusza kontener do bezczynnego stania w tle
    env_file:
      - .env
    environment:
      # Wewnątrz sieci Dockera łączymy się z kontenerem bazy danych, używając jego nazwy: 'postgres'
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public
    restart: always
    depends_on:
      postgres:
        condition: service_healthy 

volumes:
  postgres_data: # Declares the named volume for database persistence
